#!/usr/bin/bash
export DISPLAY=:0.0

result=$(cat /usr/local/sbin/makeComputerUnusable/shouldComputerBecomeUnusableToday.txt)
if [[ "$result" == yes ]]
then
        wmctrl -k on
	sleep 30
	gnome-screensaver-command -l
	wmctrl -k on
	nmcli radio wifi off
else
	nmcli radio wifi on
        echo diferenteDeYes
fi


